version: '3.9'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d
      - ./mysql:/etc/mysql/conf.d

volumes:
  db-data:
